# Generated by Django 5.1 on 2024-08-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.CharField(max_length=255)),
                ('instructor_email', models.EmailField(max_length=254)),
                ('instructor_rank', models.CharField(max_length=255)),
                ('instructor_url', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_url', models.SlugField(max_length=255, unique=True)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_role', models.CharField(max_length=255)),
            ],
        ),
    ]
